### ISSUE TITLE
List the URL of all installed extensions

### ISSUE THREAD

**Issue by csingewald** [ToasterUwU/install-gnome-extensions#1]
What about an option to list the URL of all installed extensions. This would be useful if I want to automate manually installed extensions.

somthing like :

`/home/$USER/.local/share/gnome-shell/extensions/*/metadata.json | jq -r ".url"`

**Comment by csingewald** [comment]
Ah, OK, these URLs are not the URLs in the extensions repository.

**Comment by ToasterUwU** [comment]
Hey, just saw the issue, I didn't get a notification for some reason.

I have no idea what you mean, mind clarifying a bit? Or is this just a misunderstanding from your side? @csingewald

**Comment by csingewald** [comment]
Ah, sorry, got a bit confused :) I thought it might be useful to be able to generate a list of links or ids from the installed extensions, which I could use to install the extension on a second machine, as in step 3 described.

**Comment by ToasterUwU** [comment]
So you want something like a --export-links option that gives you all the links to all the installed extensions?
